### ISSUE TITLE
Fix IntegrationTest  - ubuntu config

### ISSUE THREAD

**Issue by DenilssonMontoya** [miw-upm/apaw-practice#1023]

**Comment by DenilssonMontoya** [comment]
Fix error produced by incompatibility between ubuntu 24 and embedded mongoDB dependency version.

	at de.flapdoodle.reverse.TransitionWalker.initState(TransitionWalker.java:186)
	at de.flapdoodle.reverse.TransitionWalker.initState(TransitionWalker.java:65)
	at de.flapdoodle.embed.mongo.spring.autoconfigure.MongodWrapper.start(MongodWrapper.java:45)
	at java.base/java.lang.reflect.Method.invoke(Method.java:569)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeCustomInitMethod(AbstractAutowireCapableBeanFactory.java:1910)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1863)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1802)
	... 106 more
Caused by: java.lang.IllegalArgumentException: could not resolve package for GenericFeatureAwareVersion{5.0.14}:Platform{operatingSystem=Linux, architecture=X86_64, distribution=Ubuntu}
